/// This file defines the [BuildArch] enum, which specifies the CPU architectures
/// that the app is designed to run on and, consequently, the architectures supported
/// by the installer generated by [inno_bundle].
///
/// The [BuildArch] enum includes three options:
/// - [BuildArch.x64]: Represents strictly x86 architecture with 64-bit (`x86_64`).
/// - [BuildArch.x64Compatible]: Represents a 64-bit architecture with emulation in arm64 (`x86_64`).
/// - [BuildArch.arm64]: Represents the ARM 64-bit architecture (`arm64`).
///
/// The file also provides utility methods for validating and parsing configuration
/// options:
/// - [validateConfig]: Validates a configuration option to ensure it matches an accepted value.
/// - [fromOption]: Converts a string configuration option into the corresponding [BuildArch] enum value.
library;

/// The CPU Architecture that the app was designed to run on,
/// and therefore the architectures that are accepted by [inno_bundle] generated installer.
enum BuildArch {
  x64("x64os", "x64", "x86_64"),
  x64Compatible("x64compatible", "x64_compatible", "x86_64");
  // arm64("arm64", "arm64", "arm64");

  /// Inno value to be inserted into the iss script.
  final String innoValue;

  /// value to be used in the config file for this inno value.
  final String configValue;

  /// CPU architecture represented by this value.
  final String cpu;

  /// Creates a [BuildArch] instance with the given [innoValue], [configValue], and [cpu].
  const BuildArch(this.innoValue, this.configValue, this.cpu);

  /// List of literal string values to be accepted as valid value for option.
  static final acceptedOptionValues = values.map((e) => e.configValue).toList();

  /// Validate configuration option for [BuildArch].
  static String? validateConfig(dynamic option, {required String configName}) {
    if (option == null) return null;
    if (option is String && acceptedOptionValues.contains(option)) {
      return null;
    }
    return "inno_bundle.arch attribute is invalid in $configName.";
  }

  /// Parses configuration option to the desired [BuildArch].
  static BuildArch fromOption(String? option) {
    if (option == null) return BuildArch.x64Compatible;
    return values.firstWhere((e) => e.configValue == option);
  }
}
